version: 2.1
jobs:
  build:
    docker:
      - image: docker:19.03.12
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.12
      - run:
          name: Build and Push Docker Image
          command: |
            # Build the Docker image
            docker build -t $DOCKERHUB_USERNAME/backend-session:latest .

            # Authenticate with your container registry (e.g., Docker Hub)
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

            # Push the image to the registry
            docker push $DOCKERHUB_USERNAME/backend-session:latest

  deploy:
    docker:
      - image: circleci/python:3.8
    steps:
      - setup_remote_docker:
          version: 19.03.12
      - run:
          name: SSH into Remote System and Pull Docker Image
          command: |
            # Install sshpass to enter the SSH password
            sudo apt-get update && sudo apt-get upgrade && sudo apt-get install -y sshpass

            # Use sshpass to SSH into the remote system using the password
            sshpass -p $SSH_PASS ssh $SSH_USER@$SSH_HOST "docker pull $DOCKERHUB_USERNAME/backend-session:latest && docker run -d -p 9000:8080 $DOCKERHUB_USERNAME/backend-session:latest"

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          context:
            - Deploy

      - deploy:
          requires:
            - build
          context:
            - Deploy
