name: Build and Deploy to Server

on:
  push:
    branches:
      - main # Adjust the branch as needed

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Create env file
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
          cat .env

      - name: Build and push Docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          docker buildx create --use
          docker buildx build --push -t $DOCKER_USERNAME/backend-session:latest .

  Deploy:
    runs-on: ubuntu-latest
    needs: Build

    steps:
      - name: SSH and Deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: |
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/backend-session:latest 
            sudo docker run -d -p 9000:8080 ${{ secrets.DOCKER_USERNAME }}/backend-session:latest
