name: Build and Deploy to GCE

on:
  pull_request:
    types:
      - closed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH keys
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to GCE
        run: |
          # Replace this with your deployment commands
          ssh -o StrictHostKeyChecking=no -i $SSH_AUTH_SOCK user@your-gce-instance-ip 'bash -s' << 'ENDSSH'
            cd /repo/backend-session
            sudo docker compose down
            git pull origin main
            npm install
            sudo docker compose up --build
            # Other deployment commands
          ENDSSH